# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('fee', models.FloatField(blank=True)),
                ('camera', models.CharField(choices=[('1', 'One'), ('Banana', 'Two'), ('Turtle', 'Pie')], max_length=255)),
                ('services', models.CharField(choices=[('Go home', 'One'), ('Or not', 'Two')], max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=255)),
                ('photo_styles', models.CharField(choices=[('Old Timey', 'One'), ('New Timey', 'Two')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
